# RT-Thread building script for bridge

import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
src/hc32f460_adc.c
src/hc32f460_clk.c
src/hc32f460_dmac.c
src/hc32f460_efm.c
src/hc32f460_gpio.c
src/hc32f460_icg.c
src/hc32f460_interrupts.c
src/hc32f460_pwc.c
src/hc32f460_timer0.c
src/hc32f460_sram.c
src/hc32f460_utility.c
src/hc32f460_exint_nmi_swi.c
src/hc32f460_usart.c
src/hc32f460_i2c.c
""")

#src += Glob('HC32F4A0_StdPeriph_Driver/src/*.c')

# if GetDepend(['RT_USING_SERIAL']):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_usart.c']
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_tmr0.c']

# if GetDepend(['RT_USING_I2C']):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_i2c.c']

# if GetDepend(['RT_USING_SPI']):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_spi.c']
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_qspi.c']

# if GetDepend(['RT_USING_CAN']):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_can.c']

# if GetDepend(['RT_USING_ADC']):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_adc.c']

# if GetDepend(['RT_USING_RTC']):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_rtc.c']

# if GetDepend(['RT_USING_WDT']):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_wdt.c']
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_swdt.c']
    
# if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM'] or GetDepend(['RT_USING_PULSE_ENCODER'])):
#     src += ['HC32F4A0_StdPeriph_Driver/src/hc32f4a0_tmra.c']


#add headfile script 
path = [cwd + '/inc',cwd+'/CMSIS']

# CPPDEFINES = ['USE_DDL_DRIVER', rtconfig.MCU_TYPE, '__DEBUG']

# group = DefineGroup('HC32_StdPeriph', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
group = DefineGroup('HC32_StdPeriph', src, depend = [''], CPPPATH = path)

Return('group')
